# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site.

# Theme Settings
remote_theme            : "mmistakes/minimal-mistakes"
minimal_mistakes_skin   : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                  : "en-US"
title                   : "Shivangi Ambardar"
title_separator         : "-"
name                    : "Shivangi Ambardar"
description             : "PhD Candidate in Economics at the University of Illinois Urbana-Champaign."
url                     : "https://ambardars.github.io"
repository              : "ambardars/ambardars.github.io"

# Analytics
analytics:
  provider              : "google-gtag" 
  google:
    tracking_id         : "G-0DDL94YS6K"

# Site Author
author:
  name                  : "Shivangi Ambardar"
  avatar                : "/assets/images/bio-photo.jpg" # path of avatar image
  bio                   : "PhD student in Economics at UIUC. Outside of academia, I enjoy the focus and discipline of flying sailplanes. ✈️"
  location              : "Urbana, Illinois"
  email                 : "sambar3@illinois.edu"
  links:
    - label             : "Email"
      icon              : "fas fa-fw fa-envelope-square"
      url               : "mailto:sambar3@illinois.edu"


# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
